### ISSUE TITLE
Unabe to install evm

### ISSUE THREAD

**Issue by bingen** [CoinCulture/evm-tools#14]
When trying to install with `make` (or with `go install github.com/CoinCulture/evm-tools/evm`) I get the following error:
```
# github.com/CoinCulture/evm-tools/vendor/github.com/ethereum/go-ethereum/core
vendor/github.com/ethereum/go-ethereum/core/block_validator.go:147:19: not enough arguments in call to set.New
	have ()
	want (set.SetType)
```
I'm using Debian with Go version 1.11.4

**Comment by ebuchman** [comment]
Did you run `dep ensure` first?

**Comment by bingen** [comment]
Yes, I did, but I got the following error:
```
> dep ensure
grouped write of manifest, lock and vendor: failed to export gopkg.in/fatih/set.v0: fatal: failed to unpack tree object 27c40922c40b43fe04554d8223a402af3ea333f3
: exit status 128
```
Then I found somewhere that `dep ensure -update` would fix it, so I did that, but I guess not.

**Comment by ebuchman** [comment]
Is this on a fresh checkout of the repo? Can you try deleting the `vendor` dir if it exists, or doing a fresh checkout of the repo, and trying again?

**Comment by xwvvvvwx** [comment]
I also have the same issue with `dep ensure` on a fresh checkout of the repo (`nixos-19.03`).

**Comment by ebuchman** [comment]
My apologies, this was indeed broken. I must have had some cached data. I was able to replicate the issue on a fresh GOPATH. It should work now. Please open a new issue if it still doesn't.

Hopefully implementing https://github.com/CoinCulture/evm-tools/issues/13 will help do away with these issues too.

Thanks for your patience

**Comment by bingen** [comment]
Yes, now it woks. Thank you so much!
