### ISSUE TITLE
Documentation error:  pysha's sha3_256() used instead of keccak_256()

### ISSUE THREAD

**Issue by deklerkmc** [CoinCulture/evm-tools#3]
![screen shot 2017-08-12 at 10 26 06 am](https://user-images.githubusercontent.com/965948/29239487-0c7cd552-7f50-11e7-9099-9441d6e42ed2.png)

`$ python -c "import sha3; print sha3.sha3_256('').hexdigest()"` should be `python -c "import sha3; print sha3.keccak_256('').hexdigest();"`

**Comment by s-matthew-english** [comment]
sort of unrelated question- does this repo still work for testing evm?

**Comment by ebuchman** [comment]
> sort of unrelated question- does this repo still work for testing evm?

Not at the moment but I'm working on fixing it.

**Comment by ebuchman** [comment]
Re the original issue - the libraries were updated. I will update the guide to pin to the correct version. Thanks!
