### ISSUE TITLE
Migrate to dep

### ISSUE THREAD

**Issue by thomaseizinger** [CoinCulture/evm-tools#5]
The [`glide`](https://github.com/Masterminds/glide) project used in this repo [mentions](https://github.com/Masterminds/glide#golang-dep) in its documentation that one should migrate to  [`dep`](https://github.com/golang/dep) as it is now the more official way to manage dependencies in a go project.

There is a documentation on how to migrate to dep: https://golang.github.io/dep/docs/migrating.html

**Comment by ebuchman** [comment]
Done, thanks!
