### ISSUE TITLE
Typo or missing sentence.

### ISSUE THREAD

**Issue by mattaereal** [CoinCulture/evm-tools#8]
At the end of the second paragraph of the Overview from the Guide there's an unfinished sentence or the ending ". Each" shouldn't go there.

> A number of opcodes, like SHA3, CREATE, and RETURN, take arguments off the stack that refer to positions and sizes in memory, allowing them to operate on a contiguous array of memory. Each

**Comment by ebuchman** [comment]
Fixed, thanks!
